apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: nicopaez/pingapp:4.0.0
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      httpGet:
            host:
            scheme: HTTP
            path: /get
            port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
