apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: nicopaez/pingapp:4.0.0
    livenessProbe:
      httpGet:
            host:
            scheme: HTTP
            path: /get
            port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
